version: "3.8"
services:
  gw-server:
    build: ./gw-server
    container_name: gw-server
    env_file:
      - ./gw-server/.env
    ports:
      - "8000:8000"
    volumes:
      - ./gw-server:/app
      - /app/node_modules
  postgres: 
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./gw-db:/data/db
    environment:
      - POSTGRES_PASSWORD=gg@320
      - POSTGRES_USER=postgres
      - POSTGRES_DB=goodwords
    restart: always
